# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    verify-gradle-wrapper:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3.5.0

    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jdk: [11, 15]
        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-
            - name: Set up JDK
              uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
              with:
                  distribution: adopt
                  java-version: ${{ matrix.jdk }}
            - run: chmod +x gradlew
            - run: ./gradlew build --stacktrace --warning-mode all
