# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    verify-gradle-wrapper:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
            - uses: gradle/wrapper-validation-action@e2c57acffb2c9aa5a8dc6eda2bbae0b6e495bd4c # tag=v1.0.3

    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jdk: [11, 15]
        steps:
            - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
            - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3.0.11
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-
            - name: Set up JDK
              uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d # tag=v3
              with:
                  java-version: ${{ matrix.jdk }}
            - run: chmod +x gradlew
            - run: ./gradlew build --stacktrace --warning-mode all
